motoristas = ['Bruno Martins', 
              'João Santos',
              'Paula Durães', 
              'David Figueirinha', 
              'Telmo Ferreira', 
              'Cristóvão Santos', 
              'Artur Barreira',
              'Francisco Santos',
              'Diogo Carreira',
              'Nuno Serra',
              'Jorge Ladeira',
              'Isidro Esperança',
              'Marco Pedrosa',
              'Ricardo Mota',
              'César Fernandes',
              'Rúben Marques']

socorristas = ['Bruno Martins',
               'João Santos',
               'Paula Durães',
               'David Figueirinha',
               'Telmo Ferreira',
               'Diogo Carreira',
               'Nelson Mota',
               'João Pedrosa',
               'Ricardo Mota',
               'Cátia Domingues',
               'Vânia Silva',
               'Neuza Carvalho',
               'Liliana Marques',
               'Rúben Marques',
               'Alexandre Fernandes']

estagiarios = ['Andreia Leal',
               'Maria Carreira']