#You are working for the school principal. We have a database of school students:
#    school = {'Bobby', 'Tammy', 'Jammy', 'Sally', 'Danny'}
#During class, the teachers take attendance and compile it into a list
#attendance_list = ['Jammy', 'Bobby', 'Danny', 'Sally']
#Using what you learned about sets, creat a peice of code that the school principal can use to immediately find out who missed class
#so they can call the parents.
#(Imagine if the list had 1000s of students. The principal can use the lists generated by the teachers + the school database to use
#python and make his/her job easier):
#Find the students that miss class.

school = {'Bobby', 'Tammy', 'Jammy', 'Sally', 'Danny'}

attendance_list = ['Jammy', 'Bobby', 'Danny', 'Sally']

print(school.difference(attendance_list))